### ISSUE TITLE
Init class TDTEngine  for project TagDataTranslation-net

### ISSUE THREAD

**Issue by Gaetan6511** [dannyhaak/TagDataTranslation#2]
In the  foreach (string filename in assembly.GetManifestResourceNames())
for csv treatment,
string scheme = filename.Split('-')[2].Split('.')[0];
the indice of spilt (filename.Split('-')[2]) is out of range.

the problem is in bold font versus bold italic font :

#if NETSTANDARD1_4
            var assembly = typeof(TagDataTranslation.TDTEngine).GetTypeInfo().Assembly;
            var schemeFilenameStart = "**_TagDataTranslation-netstandard.Schemes._**";
            var filterFilenameStart = "**_TagDataTranslation-netstandard.FilterValueTables."_**;
#else
            var assembly = Assembly.GetExecutingAssembly ();
            var schemeFilenameStart = "**TagDataTranslationnet.Schemes.**";
            var filterFilenameStart = "**TagDataTranslationnet.FilterValueTables.**";
#endif
**Possible solution:** 
_change_
string scheme = filename.Split('-')[2].Split('.')[0];
_to_
#if NETSTANDARD1_4
                            string scheme = filename.Split('-')[2].Split('.')[0];
#else
                            string scheme = filename.Split('-')[1].Split('.')[0];
#endif
Best regard
Gaetan

**Comment by dannyhaak** [comment]
Thanks for your feedback, and my extremely late reply. The issue has been fixed, thanks for reporting.
